name: dt-karel
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- pytorch
- torchvision
- pytorch-cuda=12.1
- gymnasium
- einops
- transformers
- wandb
- pandas
- pytables
- scipy
- h5py
- optuna
- progressbar2
- colorlog
- pyparsing
- chardet
- matplotlib
- pip
- pip:
  - karel
  - git+ssh://git@github.com/AbhijeetKrishnan/grammar-synthesis.git#egg=grammar_synthesis
