name: decision-transformer-karel
channels:
- defaults
- conda-forge
dependencies:
- python=3.11.*
- cudatoolkit=11.8
- einops>=0.6.1
- transformers>=4.30.2
- wandb
- pandas
- pytables
- scipy
- h5py
- progressbar2
- colorlog
- pyparsing
- chardet
- matplotlib
- pip
- pip:
  - --extra-index-url https://download.pytorch.org/whl/cu118
  - torch >= 2.0.1
  - karel >= 1.3.0
  - -e git+git@github.com:AbhijeetKrishnan/grammar-synthesis.git#egg=grammar_synthesis
