# Hyperparameters for training a decision transformer on the harvester Karel task
# found by tuning using Optuna
%YAML 1.1
---
task:
  env: karel
  karel_task: harvester
  dataset: playback
  seed: 75092
  num_eval_episodes: 64
training:
  env_targets: "1"
  scale: 1.0
  mode: delayed
  device: cuda
  model_type: dt
  log_to_wandb: false
  format: h5
hyperparams:
  K: 50
  pct_traj: 0.01
  batch_size: 64
  embed_dim: 128
  n_layer: 2
  n_head: 2
  activation_function: relu
  dropout: 0.007
  learning_rate: 3.2e-4
  weight_decay: 1.0e-3
  warmup_steps: 150
  max_iters: 10
  num_steps_per_iter: 1500
  use_seq_state_embedding: true
  sample: length
...