# Hyperparameters for training a decision transformer on the cleanHouse Karel task
# found by tuning using Optuna TODO:
%YAML 1.1
---
task:
  env: karel
  karel_task: cleanHouse
  dataset: playback
  seed: 75092
  num_eval_episodes: 64
training:
  env_targets: "1"
  scale: 1.0
  mode: delayed
  device: cuda
  model_type: dt
  log_to_wandb: false
  format: h5
hyperparams:
  K: 50
  pct_traj: 0.01
  batch_size: 64
  embed_dim: 128
  n_layer: 4
  n_head: 4
  activation_function: relu
  dropout: 4.5e-2
  learning_rate: 1.1e-4
  weight_decay: 2.6e-3
  warmup_steps: 5000
  max_iters: 10
  num_steps_per_iter: 9000
  use_seq_state_embedding: true
  sample: length
...
