# Hyperparameters for training a decision transformer on the fourCorners Karel task
# found by tuning using Optuna
%YAML 1.1
---
task:
  env: karel
  karel_task: fourCorners
  dataset: playback
  seed: 75092
  num_eval_episodes: 64
  eval_seeds: [70965,  85006, 50916, 57114, 91771] # unused
training:
  env_targets: [2.2]
  scale: 1.0
  mode: delayed
  device: cuda
  model_type: dt
  log_to_wandb: true
  format: h5
hyperparams:
  K: 50
  pct_traj: 0.01
  batch_size: 32
  embed_dim: 128
  n_layer: 4
  n_head: 1
  activation_function: relu
  dropout: 0.03
  learning_rate: 5.0e-3
  weight_decay: 1.0e-3
  warmup_steps: 800
  max_iters: 10
  num_steps_per_iter: 1000
  use_seq_state_embedding: true
  sample: length
...