name: decision-transformer-microrts
channels:
- pytorch
- nvidia
dependencies:
- python>=3.11
- anaconda
- cudatoolkit=11.8
- numpy
- pip
- pip:
  - gymnasium
  - numpy
  - torch
  - transformers
  - wandb
  - JPype1
  - peewee
  - spyder
  - lark
